services:
  downtify:
    image: henriquesebastiao/downtify:latest
    container_name: downtify
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped

  hera:
    build: .
    container_name: hera
    depends_on:
      - downtify
    ports:
      - "8080:8080"
    environment:
      - LASTFM_API_KEY=
      - LASTFM_USERNAME=
      - DOWNTIFY_API_URL=http://downtify:8000
      - MUSIC_DOWNLOAD_DIR=/music/downloads
      - APP_CONFIG_DIR=/config
    volumes:
      - ./downloads:/music/downloads
      - ./config:/config
    restart: unless-stopped