services:
  downtify:
    image: henriquesebastiao/downtify:latest
    container_name: hera-downtify
    volumes:
      - /DATA/Media/Music/hera-downloads:/downloads
    networks:
      - hera-net
    restart: unless-stopped

  hera:
    image: athuul/hera:latest
    container_name: hera
    depends_on:
      - downtify
    ports:
      - "8080:8080"
    environment:
      - DOWNTIFY_API_URL=http://downtify:8000
      - MUSIC_DOWNLOAD_DIR=/music/downloads
      - APP_CONFIG_DIR=/config
    volumes:
      - /DATA/Media/Music/hera-downloads:/music/downloads
      - /DATA/AppData/hera-music/config:/config
    networks:
      - hera-net
    restart: unless-stopped

networks:
  hera-net:
    driver: bridge