services:
  hera:
    build: .
    container_name: hera
    depends_on:
      - downtify
    ports:
      - "8080:8080"
    environment:
      - DOWNTIFY_API_URL=http://downtify:8000
      - MUSIC_DOWNLOAD_DIR=/music/downloads
      - APP_CONFIG_DIR=/config
    volumes:
      - /DATA/Media/Music/hera-downloads:/music/downloads
      - /DATA/AppData/hera-music/config:/config
    restart: unless-stopped

  downtify:
    image: henriquesebastiao/downtify:latest
    container_name: hera-downtify
    volumes:
      - /DATA/Media/Music/hera-downloads:/downloads
    restart: unless-stopped